#!/usr/bin/env ruby

require 'rubygems'
require 'fileutils'
require 'bundler/setup'

Bundler.require(:default)

ENV["APP_ENV"] ||= "production"

lib_dir = File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib'))
log_dir = File.expand_path(File.join(File.dirname(__FILE__), '..', 'log'))

$:.unshift lib_dir

require 'command_interpretor'
require 'simulation/robot'

if __FILE__ == $0
  FileUtils.mkdir log_dir unless Dir.exist? 'log'

  # create Grid with known size dimensions
  grid  = Simulation::Grid.new(5,5)
  # initialize the Robot with Grid to move on
  robot = Simulation::Robot.new(grid)

  cmd_interpretor = CommandInterpretor.new(robot)
  File.open("./scripts/command.txt").each_line do |cmd_str|
    begin
      puts cmd_str
      cmd = cmd_interpretor.interpret(cmd_str)
      cmd.execute
    rescue => e
      Simulation.logger.error("Invalid command: #{cmd_str}. Reading next command.")
    end
  end
end
